# Generated by Django 5.1.7 on 2026-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
