# Generated by Django 5.2.7 on 2026-01-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorspace', '0002_brand_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandproducts',
            name='product_sizes',
            field=models.TextField(),
        ),
    ]
