# Generated by Django 5.1.7 on 2026-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_sneaker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
